# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasualtyDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tweet', models.TextField()),
                ('cd_location', models.TextField(blank=True, null=True)),
                ('cd_tweet_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_casualty_damage', models.IntegerField(default=0)),
                ('n_caution_advise', models.IntegerField(default=0)),
                ('n_donation', models.IntegerField(default=0)),
                ('n_other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CautionAdvise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tweet', models.TextField()),
                ('cd_location', models.TextField(blank=True, null=True)),
                ('cd_tweet_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tweet', models.TextField()),
                ('cd_location', models.TextField(blank=True, null=True)),
                ('cd_tweet_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tweet', models.TextField()),
                ('cd_location', models.TextField(blank=True, null=True)),
                ('cd_tweet_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
