# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField()),
                ('text_category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.TextField(default='data'),
        ),
    ]
