# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20180105_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CautionAdvise',
            new_name='CautionAdvice',
        ),
        migrations.RenameField(
            model_name='categoriescount',
            old_name='n_caution_advise',
            new_name='n_caution_advice',
        ),
    ]
