# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20180105_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_query', models.TextField()),
            ],
        ),
    ]
